api: null
binary_sensor:
- id: button
  name: Switch feeder
  on_press:
  - switch.turn_on: relay
  pin:
    inverted: true
    mode:
      input: true
      pullup: true
    number: GPIO4
  platform: gpio
- name: Status
  platform: status
esp8266:
  board: esp01_1m
esphome:
  name: wifi_smart_fish_feeder
light:
- id: led
  output: blue_led
  platform: monochromatic
logger: null
ota: null
output:
- id: blue_led
  pin:
    inverted: true
    number: GPIO5
  platform: esp8266_pwm
sensor:
- internal: true
  name: Counter/min
  pin: GPIO12
  platform: pulse_meter
  total:
    name: Counter feeder
    unit_of_measurement: time(s)
  unit_of_measurement: time(s)
switch:
- id: relay
  name: Relay feeder
  on_turn_on:
  - light.turn_on: led
  - delay: 3s
  - switch.turn_off: relay
  - light.turn_off: led
  pin: GPIO14
  platform: gpio
  restore_mode: ALWAYS_OFF
wifi:
  password: !secret 'wifi_password'
  ssid: !secret 'wifi_ssid'
