api: null
captive_portal: null
esphome:
  board: nodemcuv2
  name: livingroom
  platform: ESP8266
logger: null
ota: null
wifi:
  ap:
    password: !secret 'livingroom_fallback_password'
    ssid: !secret 'livingroom_fallback_ssid'
  password: !secret 'livingroom_password'
  ssid: !secret 'livingroom_ssid'
