substitutions:
  name: maxpilot_ch2
  ch_name: "CH2"
  ssr1_pin: D3
  ssr2_pin: D7
  uptime_name: "Uptime Sensor"
  temp_sensor_entity: "sensor.atc_501e_temperature"
  temp_sensor_internal: "false"

packages:
  core: !include common/core.yaml
  wifi: !include common/wifi.yaml
  maxpilot: !include common/maxpilot.yaml
  climate: !include common/maxpilot_climate.yaml

esphome:
  name: ${name}
