api: null
esp8266:
  board: d1_mini
  restore_from_flash: true
esphome:
  name: maxpilot_sdb
logger: null
ota:
  platform: esphome
sensor:
- name: Uptime Sensor
  platform: uptime
  type: seconds
switch:
- id: maxpilot_sdb_ssr1
  name: SSR 1 SDB
  pin:
    inverted: true
    number: D3
  platform: gpio
  restore_mode: RESTORE_DEFAULT_OFF
- id: maxpilot_sdb_ssr2
  name: SSR 2 SDB
  pin:
    inverted: true
    number: D7
  platform: gpio
  restore_mode: RESTORE_DEFAULT_OFF
text_sensor:
- name: ESPHome Version
  platform: version
wifi:
  password: !secret 'wifi_password'
  ssid: !secret 'wifi_ssid'
