api: null
esphome:
  board: d1_mini
  name: maxpilot1
  platform: ESP8266
logger: null
ota: null
switch:
- id: ssr1
  name: SSR 1
  pin:
    inverted: true
    number: D3
  platform: gpio
- id: ssr2
  name: SSR 2
  pin:
    inverted: true
    number: D4
  platform: gpio
wifi:
  password: !secret 'wifi_password'
  ssid: !secret 'wifi_ssid'
