substitutions:
  name: mitsucouloir
  friendly_name: mitsucouloir
  climate_id: hpcouloir
  remote_temp_sensor: sensor.temperature_couloir
  tx_pin: TX
  rx_pin: RX

packages:
  core: !include common/core.yaml
  wifi: !include common/wifi.yaml
  mitsubishi: !include common/mitsubishi.yaml

esphome:
  name: ${name}

esp8266:
  board: esp01_1m

logger:
  hardware_uart: UART1
  level: INFO
