api: null
esp8266:
  board: d1_mini
  restore_from_flash: true
esphome:
  name: receiver_test
logger: null
ota: null
remote_receiver:
  buffer_size: 2kb
  dump:
  - rc_switch
  filter: 250us
  idle: 4ms
  pin: D1
  tolerance: 50%
remote_transmitter:
  carrier_duty_percent: 100%
  pin: D2
switch:
- name: Piscine ONOFF
  optimistic: true
  platform: template
  turn_off_action:
  - remote_transmitter.transmit_rc_switch_raw:
      code: '01011110000011011000111'
      protocol: 1
      repeat:
        times: 5
        wait_time: 0s
  turn_on_action:
  - remote_transmitter.transmit_rc_switch_raw:
      code: '010111100000110110000000'
      protocol: 1
      repeat:
        times: 5
        wait_time: 0s
wifi:
  password: !secret 'wifi_password'
  ssid: !secret 'wifi_ssid'
