api: null
dallas:
- pin: D1
esp8266:
  board: d1_mini
esphome:
  name: temperature_test
logger: null
ota: null
sensor:
- address: 17582057622880321320
  name: temperature_ballon
  platform: dallas
wifi:
  password: !secret 'wifi_password'
  ssid: !secret 'wifi_ssid'
