api: null
esp8266:
  board: d1_mini
esphome:
  name: temperature_esp
i2c:
  scl: D6
  sda: D5
logger: null
one_wire:
- pin: D1
  platform: gpio
ota:
  platform: esphome
sensor:
- address: 11584884166787096872
  name: ballon_temperature
  platform: dallas_temp
- address: 118
  humidity:
    name: garage_humidity
  platform: bme280_i2c
  pressure:
    name: garage_pressure
  temperature:
    name: garage_temperature
  update_interval: 60s
- id: uptime_seconds
  platform: uptime
text_sensor:
- name: ESPHome Version
  platform: version
wifi:
  password: !secret 'wifi_password'
  ssid: !secret 'wifi_ssid'
